theme: dimension
deploy:
  type: git                                                      # 设置发布类型，如git     
  repository: git@github.com:Liar-lwz/Liar-lwz.git   # 设置repository对应的链接 选择ssh
  branch: master                                                 # 设置提交到的分支
  message: Site updated at {{ now("YYYY-MM-DD HH:mm:ss") }}      # 设置我们提交的信息
